#!/bin/bash

# Backup script for data volumes of the api-vmware container.
# Should be placed in /etc/cron.weekly

PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin

# Grab some settings.
[ -r /etc/default/api-vmware ] && . /etc/default/api-vmware

now=`date +%Y%m%d-%H.%M`
api="api-vmware"

# Name of the container volumes that shoul be backed up.
vols=(api-vmware api-vmware-cacerts)
bckDir="/home/bck/${api}/volumes"
containerVolDir="/var/lib/containers/storage/volumes"

# Number of days of retention: delete backups older than this number of days.
if echo $API_VMWARE_VOL_RETENTION | grep -Eq '^[0-9]+$'; then 
    retention=$API_VMWARE_VOL_RETENTION
else
    retention=120
fi


cd $containerVolDir || exit 1

for vol in ${vols[@]}; do
    bckFile="${vol}_${now}.tar.xz"

    tar cfJp ${bckDir}/$bckFile $vol && chmod 400 ${bckDir}/${bckFile}
done

# The backup script should run once a week.
# Delete backups older than $retention days.
for vol in $vols; do
    find $bckDir -name "${vol}_*" -mtime +${retention} -exec rm -f {} \;
done

